project:
  type: website

website:
  title: "ISSS608 VA G10 Project Page"
  navbar:
    left:
      - href: project_proposal.qmd
        text: Project Proposal
      - href: https://isss608-apr2023-g10.shinyapps.io/G10_Project_Shiny/
        text: Project Shiny Application
      - href: user_guide.qmd
        text: User Guide for Project Shiny App
    right:
      - href: index.qmd
        text: Home

format:
  html:
    theme: minty
    css: styles.css
    toc: false
    page-layout: full

editor: visual

